In [1]:
import numpy as np

# 你的代码：
# 1. 创建1到12的一维数组
arr = np.arange(1, 13)
# 2. 重塑为3行4列的二维数组
arr_2d = arr.reshape(3, 4)

# 打印结果
print("重塑后的二维数组：")
print(arr_2d)
print("数组维度（ndim）：", arr_2d.ndim)
print("数组形状（shape）：", arr_2d.shape)
print("元素总个数（size）：", arr_2d.size)

重塑后的二维数组：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
数组维度（ndim）： 2
数组形状（shape）： (3, 4)
元素总个数（size）： 12


In [2]:
import numpy as np

# 你的代码：
# 1. 创建浮点数组
arr_float = np.array([1.5, 2.6, 3.7, 4.8])
# 2. 转换为32位整数
arr_int32 = arr_float.astype(np.int32)

# 打印转换前后结果
print("转换前数组：", arr_float)
print("转换前数据类型：", arr_float.dtype.name)
print("转换后数组：", arr_int32)
print("转换后数据类型：", arr_int32.dtype.name)


转换前数组： [1.5 2.6 3.7 4.8]
转换前数据类型： float64
转换后数组： [1 2 3 4]
转换后数据类型： int32


In [3]:
import numpy as np

# 创建二维数组
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 切片操作：取前两行，第2到第3列（索引从0开始）
result = arr[:2, 1:3]

print(result) 

[[2 3]
 [6 7]]


In [4]:
import numpy as np

# 创建一维数组
arr = np.array([10, 15, 20, 25, 30, 35])

# 1. 花式索引：提取索引为0, 2, 4的元素
fancy_index = arr[[0, 2, 4]]

# 2. 布尔索引：提取所有大于20的元素
bool_index = arr[arr > 20]

print("花式索引结果：", fancy_index)
print("布尔索引结果：", bool_index)

花式索引结果： [10 20 30]
布尔索引结果： [25 30 35]


In [5]:
import numpy as np

# 你的代码：
# 创建形状为 (3, 4) 的全0数组
arr_a = np.zeros((3, 4))
# 创建一维数组
arr_b = np.array([1, 2, 3, 4])

# 利用广播机制相加
result = arr_a + arr_b

print(result)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [6]:
import numpy as np

# 你的代码：
# 给定数组
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])

# 1. 计算数组 x 中每个元素的平方根
sqrt_x = np.sqrt(x)

# 2. 用 np.maximum 找出对应位置上的最大值
result = np.maximum(sqrt_x, y)

print("x 的平方根：", sqrt_x)
print("对应位置最大值：", result)

x 的平方根： [1. 2. 3. 4.]
对应位置最大值： [2. 2. 4. 5.]


In [7]:
import numpy as np

# 你的代码：
# 创建形状为 (2, 3, 4) 的三维数组
arr = np.arange(24).reshape((2, 3, 4))

# 使用 transpose() 转换轴顺序为 (1, 0, 2)
transposed_arr = arr.transpose((1, 0, 2))

# 打印转换后数组的形状
print("转换后数组的形状：", transposed_arr.shape)

转换后数组的形状： (3, 2, 4)


In [8]:
import numpy as np

# 你的代码：
# 给定数组
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])

# 使用 np.where() 进行条件选择
result = np.where(arr_con, arr_x, arr_y)

print("条件选择结果：", result)

条件选择结果： [1 6 7]


In [12]:
import numpy as np

# 创建指定二维数组
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])

# 1. 计算所有元素的算术平均值
mean_value = arr.mean()

# 2. 沿axis=0方向（按列）排序
arr.sort(axis=0)

print("数组所有元素的算术平均值：", mean_value)
print("按列排序后的数组：")
print(arr)
arr.mean(axis=1)

数组所有元素的算术平均值： 3.888888888888889
按列排序后的数组：
[[3 2 2]
 [4 3 2]
 [6 6 7]]


array([2.33333333, 3.        , 6.33333333])

In [11]:
import numpy as np

# 1. 设置随机数种子为10，保证结果可复现
np.random.seed(10)

# 2. 生成两个形状为(2, 2)、服从[0,1)均匀分布的随机矩阵
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)

# 3. 使用dot()方法计算矩阵点积
dot_result = np.dot(A, B)

print("随机矩阵A：")
print(A)
print("\n随机矩阵B：")
print(B)
print("\n矩阵A与B的点积结果：")
print(dot_result)

随机矩阵A：
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]

随机矩阵B：
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]]

矩阵A与B的点积结果：
[[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
